sourceDir <- getSrcDirectory(function(dummies) {dummies})
setwd(sourceDir)
if((any(grepl("xlsx",installed.packages())))==FALSE)
  install.packages("xlsx")
library(rJava)
library(xlsxjars)
library(xlsx)
data<-read.xlsx("NUTRITION.xlsx",sheetIndex=1)
data<-data[,c('sugars','rating')]
sugar<-data$sugars
rating<-data$rating
corrrelation<-cor(data$sugars,data$rating,method="pearson")
cat("Correlation comes out to be",corrrelation)
lm<-lm(rating~sugar)
lm2<-lm(rating~poly(sugar,2))
lm3<-lm(rating~poly(sugar,3))
plot(sugar,rating,col="blue")
lines(sugar,predict(lm,data.frame(sugar)),col="red")
lines(sugar,predict(lm2,data.frame(sugar)),col="yellow")
lines(sugar,predict(lm3,data.frame(sugar)),col="purple")
summary(lm)
summary(lm2)
summary(lm3)
cat("Fromt the summary of linear,quadratic and cubic models as show above\n")
cat("We see R squared values is max for quadratic regression")
cat("\nHence Quadratic is the best fit\n")